### ISSUE TITLE
Issue with Inverted power state, and IR Receiver settings

### ISSUE THREAD

**Issue by orthobots** [SodaWithoutSparkles/esphome-daikin64#2]
Hi there!

Great work on compiling the updated IR Libraries for ESPHome, it works fine on my ESP8266. 
Issues i'm having - Inverted power state with the DAIKIN64 AC units where on turns the ac off and vice versa - not a new issue, but its been apparently resolved? for some users with the newer updated libraries, but no actual description on how it was resolved

Also, i noticed that changes made via the remote aren't updated in the climate control.  

Am using the YAML from your repository,
I've also defined my IR Receiver and am able to receive pronto codes from the Remote. 
Issue I think is these codes aren't being translated and updated in HA

**Comment by SodaWithoutSparkles** [comment]
As `daikin64` is a "power toggle" protocol, state inversion will happen if you controlled it with a physical remote.

My solution is to add a sensor to detect if the AC is actually on. Thats what the `ac_status` thing is for. If the AC is on, `ac_status` should also be on. Then, the code for the remote control will know not to send the power toggle signal if the ac is already on and turns the ac off. But the HA entry for the climate entity wont be updated, because it dont know what modes you have set (cooling / heating / fan only / drying / fan only / etc).

Ofc the better way to do things would be to actively monitor the received IR signals and decode it, then synchronize the status. But, my IR receiver is weak and cannot receive signals if it wasnt pointing directly to it. Therefore I didnt implement it, and not that I knows how to do it anyway.

Another approach is to assume the AC can only be in cooling mode. That means treating "AC not off" as in cooling mode and synchronize with the internal status. This is probably do-able but I havent figured it out during the few hours I've been working on this.

------

I did not handle any remote receiver code. The "inverted power state" thing is not fixable without another sensor or human intervention.

Also this is already using the latest available library.

**Comment by SodaWithoutSparkles** [comment]
I've added a new example yaml (`with-real-sensor.yaml`) that works with a state sensor. If it detected mismatch between the esp's internal state and the actual air-con state, it will update the internal state. Usually this means the air-con was turned on by a physical remote. But when the esp has just rebooted, the state might have a mismatch which have to be fixed manually by triggering an update to the state sensor, or change the mode via frontend.

**Comment by orthobots** [comment]
oh thank you for that. How does the state sensor detect the air-con's actual state? My current ESP has an IR receiver in addition to an IR Blaster running off as ESP8266. Would your yaml work with the existing hardware?

**Comment by SodaWithoutSparkles** [comment]
> How does the state sensor detect the air-con's actual state?

I literally sticked a door/window sensor on the exhaust flap and relayed the information back from HA.

I used an ugly hack by communicating the desired state via a special climate control call with a special humidity value. This is needed because the scope of lambdas doesnt cross between components 


As for IR receivers, you can probably use the same trick by using a remote receiver component and a "on whatever decoded" action to trigger some sets of climate calls to set the state, and use the same special humidity number to prevent the esp from re-sending.

**Comment by SodaWithoutSparkles** [comment]
If there's no further questions, I would close this issue in a few days.
